### ISSUE TITLE
Get responsive ads working

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#1]
Get responsive ads working: I have two ad blocks right now. “Side Ad Block” does not have responsive code and “Side Ad Block 2” has responsive code. But, “Side Ad Block 2” is not responsive like it should be. 

*It takes less than an hour.*

**Comment by mamont77** [comment]
The second banner does not seem responsive. Specified a fixed width on the side of Google.
![1](https://cloud.githubusercontent.com/assets/970967/5759805/03d9aa1c-9cd9-11e4-81a6-6f89245d2960.png)
I was forced to add html wrapper
```html
<div class="adsense336">
```
![2](https://cloud.githubusercontent.com/assets/970967/5759830/34c14aae-9cd9-11e4-85b6-140444ddcca4.png)
Please check. Is that enough?

**Comment by mamont77** [comment]
I assume that the client decides responsive advertising or NOT responsive. Because I watch from time to time and have not seen responsive advertising in this block.

**Comment by mamont77** [comment]
I got it.
This works well after reloading the page.
![www fitnessjunkies com - google chrome 01-17-2015 08 24 08](https://cloud.githubusercontent.com/assets/970967/5787954/6079efda-9e22-11e4-9473-ac3cc900b34c.png)
But does not work when resizing the window. Google determines the size of the window, and then shows a suitable banner.
Demo: http://dev.fitnessjunkies.com/temp.html
Manual: https://support.google.com/adsense/answer/3543893?hl=en

Therefore we have to do html wrapper: 
```html
<div class="adsense336">
...google code...
</div>
```

**Comment by Fastone45** [comment]
Looks great!
