### ISSUE TITLE
Bio block for the author at the end of each article

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#10]
We need a small bio block for the author at the end of each article, workout and blog post. The bio should look something like the image below. It should say About “Authors Name”, have an image and have a small bio that is pulled from the authors’ user account (step 9 above). All of this information should be automatically populated based on who is listed as the author. Also, I want to put back in the date and author name listed under the title at the top of articles and workouts. The author name under the title and the author name in the bio should link to the author’s page to give them credit.
![improvements for 2 docx - google - google chrome 01-14-2015 07 44 09](https://cloud.githubusercontent.com/assets/970967/5734606/3cd61a6c-9bc1-11e4-92ed-637e6279f5f0.png)

*30-40 mins.*

**Comment by mamont77** [comment]
Result:
![bradley cooper american sniper transformation steroids or somet 01-16-2015 13 30 12](https://cloud.githubusercontent.com/assets/970967/5775567/3ae152ca-9d84-11e4-9e29-ebb403001b16.png)

**Comment by Fastone45** [comment]
Looks great!
