### ISSUE TITLE
The ability to comment

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#11]
We need the ability to comment on articles, blog posts and workouts. Step 8 will give us the ability to add commenting on articles, workouts and blog posts. Non-registered users should not be able to comment. Comments are not allowed on the homepage or category pages (Workouts, Articles, Articles/Cardio, etc) but they are allowed on specific articles, blog posts and workout pages. Comments should show a small thumbnail of the users image along with their name, which when clicked will link you back to their user profile page. Comments should show a date of the comment and also have a link to reply. (Should be somewhat like comments on http:// lkrsocialmedia.com/2014/05/4-reasons-why-you-need-help-running-your-business/?utm_content=buffer842d4&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)

*It is not hard to do. Drupal has module for this. Also need to do some tweaking and changes in design. About 1-1.5 hours.
As an alternative. We can install this https://www.drupal.org/project/disqus module instead of the native.*

**Comment by mamont77** [comment]
Ryan,
Please review: fonts, colors, sizes and other.
http://dev.fitnessjunkies.com/blog/bradley-cooper-american-sniper-transformation-steroids-or-something-else/#comment-4

Result:
![bradley cooper american sniper transformation steroids or somet 01-16-2015 14 58 57](https://cloud.githubusercontent.com/assets/970967/5776462/7684cd5a-9d90-11e4-81ae-954147c59880.png)
![bradley cooper american sniper transformation steroids or somet 01-16-2015 14 59 28](https://cloud.githubusercontent.com/assets/970967/5776463/768b657a-9d90-11e4-87d0-81c999ed351d.png)

**Comment by Fastone45** [comment]
Looks great!
