### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#12]
We need the following specific roles for registered users, authors, editors and admins. 
- Registered users - They can comment on articles, workouts and blog posts. 
- Authors - They can submit articles and workouts to be published and they can submit changes to their existing content to be updated. They cannot send newsletters or submit blog posts or pages to be created. They cannot delete content but they can submit their content for request to delete. They can upload images as part of content and updates. 
- Editors - They can do everything authors can but they can also publish the content and changes that authors request. They can send newsletters and create pages and blog posts. (Authors can submit to create articles, blog posts and workouts). Editors should not be allowed to edit blocks or views. Right now it appears they have this capability.
- Admins - They can do everything on the site. 

*This can be done for 10-20 minutes here http://www.fitnessjunkies.com/admin/people/permissions/.*

**Comment by mamont77** [comment]
At the moment, out of the box Drupal can not add unpublished material for a specific role (Authors).
If I do this, it will not be useful for other roles. So I will set up a rule, if the user's role has "Author" node is automatically unpublished after the addition.

**Comment by mamont77** [comment]
In testing!

Added:
registered_user@ex.com
author_user@ex.com
editor_user@ex.com

Password is the same login (mail).

**Comment by mamont77** [comment]
I found a few bugs that will be fixed today or tomorrow.

In process!

**Comment by mamont77** [comment]
Done. Please check carefully.

**Comment by mamont77** [comment]
![www fitnessjunkies com - mozilla firefox 01-19-2015 14 41 33](https://cloud.githubusercontent.com/assets/970967/5800593/67d911f2-9fe9-11e4-9fa5-4fdc0fd40cc5.png)

**Comment by Fastone45** [comment]
Still testing. First, I noticed that editors can configure blocks. This should only be available for admins.

**Comment by mamont77** [comment]
Administer blocks - was removed for editors role. Try again.

**Comment by Fastone45** [comment]
Looks good!
