### ISSUE TITLE
Notices and Warning showing up

### ISSUE THREAD

**Issue by Fastone45** [mamont77/fitnessjunkies#15]
While logging into multiple user accounts, I noticed the following warnings:

Notice: Undefined index: url in socialmedia_linkedin_tokens() (line 349 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/socialmedia/socialmedia.platforms.inc).
Notice: Undefined index: username in socialmedia_linkedin_tokens() (line 353 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/socialmedia/socialmedia.platforms.inc).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1024 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in _widgets_error() (line 1028 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1033 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Notice: Undefined index: username in socialmedia_linkedin_tokens() (line 353 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/socialmedia/socialmedia.platforms.inc).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1024 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in _widgets_error() (line 1028 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1033 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Notice: Undefined index: url in socialmedia_googleplus_tokens() (line 279 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/socialmedia/socialmedia.platforms.inc).
Notice: Undefined index: username in socialmedia_googleplus_tokens() (line 283 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/socialmedia/socialmedia.platforms.inc).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1024 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in _widgets_error() (line 1028 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1033 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Notice: Undefined index: username in socialmedia_googleplus_tokens() (line 283 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/socialmedia/socialmedia.platforms.inc).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1024 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in _widgets_error() (line 1028 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).
Warning: Illegal offset type in isset or empty in _widgets_error() (line 1033 of /home7/dreadno1/public_html/dev-fitnessjunkies/sites/all/modules/widgets/widgets.module).

1. What should be done about them?
2. If nothing, let's display warnings and notices like this only for admins and not editors, authors or registered users.

**Comment by mamont77** [comment]
This problem is related to #9. Fixed. I updated social.module.
