### ISSUE TITLE
Looks done (QA testing)

### ISSUE THREAD

**Issue by Fastone45** [mamont77/fitnessjunkies#16]
Ruslan, looks like we are done with this phase of development. I have more testing and product design to do and then we can open another odesk job. We should be good to close this one now. Correct?

**Comment by Fastone45** [comment]
I don't want to publish the dev code to live just yet. Let's keep it on dev and after the next iteration we will push it live.

**Comment by mamont77** [comment]
I just want to update.
Most of the settings (about 95%) is made in Drupal database, the rest is done in the php code.
So I have a request. Please add a new materials using DEV site. Because we can not move the part of the database, only completely. And I do not remember all the settings that I did.
When we transfer the site, you need to remove the live website, copy the files from the sandbox, replace the database, modify a settings.php file. Ok?

**Comment by Fastone45** [comment]
Ok, I will do testing this weekend and make sure we can go live and then we can take it from dev to live. I will leave this odesk task open a few more days to finish this.

**Comment by Fastone45** [comment]
I am still going through all testing of the features for this release so we can push it live. I hope to be done in a day or two. Once done, I will update the DEV site with content from the live site. In your comment, is the sandbox you refer to the same as the DEV site?

**Comment by mamont77** [comment]
Yes. DEV = sandbox.

**Comment by Fastone45** [comment]
Ruslan, I have finished testing the changes and they look good. I just have one questions. Can we do anything to keep the spacing on pages like this?

http://www.fitnessjunkies.com/fitness-gurus-articles/bruce-lee/
http://dev.fitnessjunkies.com/fitness-gurus-articles/bruce-lee/

Adding the WYSWYG seems to have removed the spacing. If we cannot fix it in one change, that is fine, then after the launch I will go through each page individually and make the changes. I just need to know.

So, after that I am ready for the launch to live. You requested that I make the change. Is that correct or do you want to do it?

**Comment by mamont77** [comment]
>> Can we do anything to keep the spacing on pages like this?

Fixed, but need to test.

>>Is that correct or do you want to do it?

in \sites\default\settings.php
replace 
```
      'database' => 'xxx',
      'username' => 'xxx',
      'password' => 'xxx',
$base_url
$cookie_domain
```

**Comment by Fastone45** [comment]
Ok, I will do the mirgration tonight after hours. Probably in 12 hours.

**Comment by Fastone45** [comment]
In order to test the transfer, I created a new sub domain (dev2.fitnessjunkies.com) and copied over the files, set up a new database and updated settings.php but it pulls up nothing. I will investigate the problem tomorrow and see if I can figure it out. For now, I will keep the existing site as is. Also, once we get the project live, I will close the odesk task, is that ok with you?

**Comment by mamont77** [comment]
Try to make a copy again.
I see that many of the files are missing.
ex: /home7/dreadno1/public_html/dev2/includes
PHP Fatal error:  require_once(): Failed opening required '/home7/dreadno1/public_html/dev2/includes/bootstrap.inc' 

>>I will close the odesk task, is that ok with you?

It's ok. Don't worry.

**Comment by Fastone45** [comment]
Ok, I got the site pushed live. Do you wanna check it when you have a minute? If it looks good we can close the odesk task and I will create a new one in a few weeks when I have the next steps planned out.

**Comment by Fastone45** [comment]
Looks like after I am logged in, I am redirected to dev.fitnessjunkies.com

**Comment by Fastone45** [comment]
Also, I can't get in to update the social media apps to be www instead of dev

**Comment by Fastone45** [comment]
I deleted my last two comments because I found that I didn't fully update the settings.php and that fixed those problems I was mentioning.

**Comment by Fastone45** [comment]
I updated the twitter login app but and I will go through tomorrow and create a new gmail one and I will start the submission process for facebook (I found where this is now).

**Comment by mamont77** [comment]
@Fastone45,
I checked the site. Look good to me. Yes, you can close the odesk contract, and you can create a new one at any time. I'm glad to work with you :ok_hand:

*Do you prefer to leave or remove a github repository? This is a public repository. But without a database is just a files. github charge for private repositories.*

**Comment by Fastone45** [comment]
We can leave the public repo or remove it. Doesn't matter to me!

**Comment by mamont77** [comment]
Ryan, 

Thank you so much for the nice feedback. It is very important to me. ))

**Comment by Fastone45** [comment]
Thank you as well! You deserve the nice feedback!
