### ISSUE TITLE
Comments don't show default user image

### ISSUE THREAD

**Issue by Fastone45** [mamont77/fitnessjunkies#18]
![comments](https://cloud.githubusercontent.com/assets/4911812/5889616/05f32f96-a3ee-11e4-9152-25a64520b5e3.jpg)

The default image that I set in the settings area that you sent me does not populate the comments image area.

**Comment by mamont77** [comment]
Fixed.
Results:
![bradley cooper american sniper transformation steroids or somet 01-25-2015 10 06 02](https://cloud.githubusercontent.com/assets/970967/5890860/378508ea-a47a-11e4-81d0-8264d94cbcf9.png)
![test workouts www fitnessjunkies com - google chrome 01-25-2015 10 05 24](https://cloud.githubusercontent.com/assets/970967/5890861/378837d6-a47a-11e4-88d8-ef8ebed0a3ba.png)

**Comment by Fastone45** [comment]
looks good.
