### ISSUE TITLE
WYSWYG editor

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#2]
Add a WYSWYG editor for adding images for articles, blog posts, workouts. 

*I can integrate into the drupal this editor http://ckeditor.com/demo. About 1.5 hour.*

**Comment by Fastone45** [comment]
Yes, let's try it.

**Comment by mamont77** [comment]
@Fastone45,

Not necessarily comment on every issue. I just copy the tasks from the file :-)

**Comment by mamont77** [comment]
Done. Please test.
Remind. After transferring the site to live need fix a few string in /home7/dreadno1/public_html/dev-fitnessjunkies/sites/default/settings.php.

**Comment by Fastone45** [comment]
There may be a problem. When trying to edit some nodes using the WYSWYG, it does not show up. See screenshot. 

http://dev.fitnessjunkies.com/node/213/edit/

![wyswyg](https://cloud.githubusercontent.com/assets/4911812/5804978/0b7c1a4c-9fc8-11e4-807c-1e3bad1008c3.png)

**Comment by Fastone45** [comment]
This may be a bug with the "filtered html" content type. It seems to only have a problem for that content type.

**Comment by mamont77** [comment]
Ryan,

Please review and test now.
Authenticated use - has access to plain text only and does not have access to WYSWYG.
![1](https://cloud.githubusercontent.com/assets/970967/5813778/cae342d4-a08b-11e4-8c0f-b05a65be781a.png)

Author role - has access to plain text & filtered html and have a basic WYSWYG.
![2](https://cloud.githubusercontent.com/assets/970967/5813787/0053e0fe-a08c-11e4-9060-f202413f65d9.png)

Editor and admin roles - have access to plain text & filtered html & full html and have a advance WYSWYG.
![3](https://cloud.githubusercontent.com/assets/970967/5813804/29cdb52c-a08c-11e4-9786-d0c563487fa7.png)

**Comment by Fastone45** [comment]
Advanced WYSWYG doesn't show up on blog posts for admin, editors (only on workouts and articles).

**Comment by mamont77** [comment]
Please try to switch the input format.
Let me know if this does not help.
![edit blog post bradley cooper american sniper transformation st 01-21-2015 08 14 21](https://cloud.githubusercontent.com/assets/970967/5831977/b094cf0a-a145-11e4-8677-f29f88936736.png)

**Comment by Fastone45** [comment]
Yes, that works.
