### ISSUE TITLE
Install meta tag module

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#6]
Install meta tag module so that we can modify things like page title, descriptions, etc.

*Install meta tag module takes 10 minutes. Make basic settings 20 minutes. Total 30 min.*

**Comment by mamont77** [comment]
Done.
Results for http://dev.fitnessjunkies.com/blog/bradley-cooper-american-sniper-transformation-steroids-or-something-else/ on https://developers.facebook.com/tools/debug/og/object/
![object debugger - google chrome 01-15-2015 18 12 16](https://cloud.githubusercontent.com/assets/970967/5761149/1ccc4936-9ce2-11e4-9565-f04ff6481715.png)
Results for http://dev.fitnessjunkies.com/themed-articles/bodybuilding-at-home/
![object debugger - google chrome 01-15-2015 18 17 35](https://cloud.githubusercontent.com/assets/970967/5761244/dd122a76-9ce2-11e4-8904-dcdf953b141c.png)
So you can send me another (more square) logo, I will point it in the settings of the module and the logo will be used for social networking.

**Comment by Fastone45** [comment]
Looks great! We are still working on a new logo that will have a square version. When that is done I will send it to you.
