### ISSUE TITLE
Add the ability to add a features image

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#7]
Add the ability to add a Jumbotron/hero image to the homepage, workouts page, articles page and their subcategory pages (/cardio-workouts/, /motivation/articles/, etc). This image should span the entire width of the container and take on whatever height is given in the image. This should not be a slider with multiple images. Just a large banner image like this:
![improvements for 2 docx - google - google chrome 01-14-2015 07 41 15](https://cloud.githubusercontent.com/assets/970967/5734591/e96cd7a8-9bc0-11e4-9f88-94d2b29c5022.png)

*I can modify the theme by adding a new region to this place for blocks. You can add any image (block’s content) on any page or section.  It takes 20-40 minutes. What do you think about this?*

**Comment by Fastone45** [comment]
Yes. Let's try this then I will see how it works.

**Comment by mamont77** [comment]
Done.
You can create an unlimited number of blocks and set the region and specify rules to display here http://dev.fitnessjunkies.com/admin/structure/block/ (Home / Administration / Structure / Blocks).

Example http://dev.fitnessjunkies.com/admin/structure/block/manage/block/6/configure/
![test block for top region block www fitnessjunkies com - goo 01-16-2015 09 31 44](https://cloud.githubusercontent.com/assets/970967/5772885/a078fcb8-9d62-11e4-85c6-c5cb01a6c18e.png)

**Comment by Fastone45** [comment]
It seems like there is still a padding. I would really like to have the image go from border to border as shown in the original screenshot.

**Comment by mamont77** [comment]
Fixed.
![www fitnessjunkies com - google chrome 01-20-2015 07 41 53](https://cloud.githubusercontent.com/assets/970967/5812665/fc587f14-a077-11e4-953a-ddfb9bbe772e.png)

**Comment by Fastone45** [comment]
I can't edit the image because I cannot upload a new image to replace because the advanced WYSWYG does not work on block.

**Comment by mamont77** [comment]
Same here. You should specify the FULL HTML. Try now.

**Comment by Fastone45** [comment]
Yes, looking into it now. Thanks!

**Comment by mamont77** [comment]
Can we close the issue?

**Comment by Fastone45** [comment]
It looks mostly good, but I added an image to the cardio-articles page and I would like one fix. Can we remove the white space above the block (below the bread-crumbs)?
http://dev.fitnessjunkies.com/cardio-articles/

**Comment by mamont77** [comment]
Try delete an empty <P> tag :-)
![cardio articles page top image block www fitnessjunkies com 01-22-2015 08 10 01](https://cloud.githubusercontent.com/assets/970967/5851318/294a7fd0-a20e-11e4-9fba-d537c1d34569.png)

**Comment by Fastone45** [comment]
My bad! :)
