### ISSUE TITLE
Sign up via facebook, gmail and twitter

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#8]
I would like to give users the ability to sign up to the website via facebook, gmail and twitter. We don’t need to do all 3 but we could. What is your recommendation? That way we can use their images and some information and they don’t need an additional login. However, we will need to store additional information about the user in our databases and we need a way to specify their user role (registered user, author, editor or admin).

*Of course social networks can provide a user name and email, sometimes these can provide an image. For security reasons social networks do not transmit the password. Therefore, during the user registration via social network Drupal ask a new password. There are several of similar modules for Drupal. I'll see what is better. This functional and necessary design changes will take about 3 hours.*

**Comment by Fastone45** [comment]
Ok, yes. Let me know what you find.

**Comment by mamont77** [comment]
Ryan,

Can you help me?
I installed the module. Providers must be set.
http://dev.fitnessjunkies.com/admin/config/people/hybridauth/provider/LinkedIn/?destination=admin/config/people/hybridauth
http://dev.fitnessjunkies.com/admin/config/people/hybridauth/provider/Google/?destination=admin/config/people/hybridauth
http://dev.fitnessjunkies.com/admin/config/people/hybridauth/provider/Facebook/?destination=admin/config/people/hybridauth
http://dev.fitnessjunkies.com/admin/config/people/hybridauth/provider/Twitter/?destination=admin/config/people/hybridauth

Google now works only.
http://dev.fitnessjunkies.com/user/login/ or http://dev.fitnessjunkies.com/user/register/

Later I will design and layout of icons. At this point I want to make sure that you can configure several providers.

Remember, the keys are given for the domain. When we launched the site, you need to generate new keys.

**Comment by Fastone45** [comment]
I will look into helping on this in one minute. Also, we don't want LinkedIn on this. Just facebook, twitter and google.

**Comment by Fastone45** [comment]
I will create facebook and twitter apps tomorrow and enter their keys.

**Comment by mamont77** [comment]
Thanks. Let me check too.

**Comment by Fastone45** [comment]
I created the facebook key and it worked for now. I will do more testing later and log any needed updates.

**Comment by mamont77** [comment]
Maybe it works for you, but does not work for me.

Twitter is empty http://dev.fitnessjunkies.com/admin/config/people/hybridauth/provider/Twitter/?destination=admin/config/people/hybridauth

Facebook app in devel mode (It is necessary to remove the check mark on the side of Facebook)
![1 error - mozilla firefox 01-23-2015 14 53 27](https://cloud.githubusercontent.com/assets/970967/5874964/244a0b1a-a310-11e4-9190-e3849d434407.png)

Sorry, i forced to do reopen the task.

**Comment by Fastone45** [comment]
Still working on

**Comment by mamont77** [comment]
Just went to update.
If you want, I can help.

**Comment by Fastone45** [comment]
Ok Ruslan, I set up twitter and I tested your google app and they both work. The facebook app works but it is a dev app so you have to be a developer or tester to test it. Add me as a friend on facebook and I will give you access to test the app: https://www.facebook.com/ryan.long.5074

**Comment by mamont77** [comment]
I sent you a request my friend :-)

**Comment by Fastone45** [comment]
I accepted and added you as admin to the dev and live apps.

**Comment by mamont77** [comment]
Thank U. I'll check tomorrow morning. I have 9:00 a.m. now.

**Comment by mamont77** [comment]
For some unknown reason, facebook is not working.
![5 error - mozilla firefox 01-28-2015 08 53 53](https://cloud.githubusercontent.com/assets/970967/5933603/78b779bc-a6cb-11e4-9ce4-789f98a84338.png)

**Comment by Fastone45** [comment]
Did you try again? It has always worked for me.

**Comment by mamont77** [comment]
FB doesn't work to me.
I think we can set up on live site later, not to waste time now.

**Comment by Fastone45** [comment]
ok
