### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by mamont77** [mamont77/fitnessjunkies#9]
Authors pages - Right now it looks like non-registered users cannot view user pages. (It says “Access Denied”. http://www.fitnessjunkies.com/users/jake-long/) We should open these pages up for all to see. Also, let’s not have the titles “First Name” and “Last Name”, but just show the users’ name. This page should be formatted well and include name, bio, location, image, social media and website links. We should include a thumbnail of their user image and their name. The thumbnail should come from step 8 above. The other information they should be able to edit within fitnessjunkies.com. And it should include an automatically populated list of all of the blog posts, workouts and articles that the author has published.

*I find it difficult to estimate the time.  If it's just text boxes with information about the user it’s will take about 2 hours.  In this case, I will add a few fields in the user profile, fix the design of these fields, configure the relationship between other modules.
If you want a similar profile (ex: http://bodyspace.bodybuilding.com/Phillleonard/) - it will take more time.*

**Comment by Fastone45** [comment]
Right now I just want it to be basic to include a few text fields and the basic information I mentioned above. I am working on new designs that we will build in a month or so that will make it more like the example you provided, but for now just simple.

**Comment by mamont77** [comment]
I tried to make the most simple design. Only functional. Check the result. What do you think about this?

http://dev.fitnessjunkies.com/users/jake_long/
http://dev.fitnessjunkies.com/users/ruslan_piskaryov/

**Comment by Fastone45** [comment]
Looks good except for a few things. First, let's reduce the size of the profile image so it is not so big on the full screen view. Make it maybe 20-50% smaller. Also, I don't want to display the "HybridAuth identities" to the public but I would like to have the ability to link to your facebook, linkedin, twitter page. Maybe using the user social profiles tab that we have right now? Also, right now it seems like anyone logged in can edit someone else's user profile. Is that true? Let me know if you don't understand any of this feedback.

**Comment by mamont77** [comment]
I got it))

**Comment by Fastone45** [comment]
Actually, let's change the image on the user profile page to be exactly like the image at the bottom of the articles. (Same size, square shape and border).

**Comment by mamont77** [comment]
1. the size of the profile image - Fixed.
2. I don't want to display the "HybridAuth identities" - Fixed.
3. Also, right now it seems like anyone logged in can edit someone else's user profile - This can be done only by the administrator role.
4. Maybe using the user social profiles tab that we have right now? - Done.

About "social profiles".
We can use other icons pack. Look on http://dev.fitnessjunkies.com/admin/config/media/socialmedia/ (Icon sets tab).
Also, for some unknown reason, site (socialmedia.module) displayed icons that do not have data. I think we can fix it build the handler or form_alter.
![www fitnessjunkies com - opera 01-20-2015 08 26 03](https://cloud.githubusercontent.com/assets/970967/5812984/15f483d6-a07e-11e4-9cd0-aa7bc27a067a.png)

**Comment by Fastone45** [comment]
Thanks Ruslan. The icons look fine. Yes, I would like to fix the icons so that only those that have data are displayed on the users profile. I just want four sites available (Facebook, twitter, google+ and YouTube).

**Comment by Fastone45** [comment]
Also, the icons should only show on the user pages. For some reason, right now it also shows up on this page (probably because they contain /user/ in the URL):

http://dev.fitnessjunkies.com/user/login/

**Comment by Fastone45** [comment]
Also, let's not show the RSS icon.

**Comment by mamont77** [comment]
Ryan,
Site uses this module https://www.drupal.org/project/socialmedia.
I also noticed that it is not works stably on the user page.

Can I just create four field and turn off the "Social profiles" tab?

**Comment by Fastone45** [comment]
Yes, that will be fine.

**Comment by mamont77** [comment]
1. Added new fields.
![1](https://cloud.githubusercontent.com/assets/970967/5833026/9b648b1e-a156-11e4-94ce-6d487aea0fbd.png)
2. Built output links as icons.
![2](https://cloud.githubusercontent.com/assets/970967/5833033/b4b5b7dc-a156-11e4-9147-63a65e8dff5e.png)

@Fastone45, please review.

**Comment by Fastone45** [comment]
Icons and things look good. Let put the bio above the website link and the social media links. See how they are below right now on my profile:

http://dev.fitnessjunkies.com/users/ryan_long/

Also, if we don't need it anymore, did you uninstall the module that provided the social media functionality with the bug? I only ask because I see the "Social Profiles" tab when I edit my profile page. I would expect this tab to disappear if we don't need it anymore.

**Comment by mamont77** [comment]
1. Fixed.

2. We can not uninstall the module, it is uses on other pages.
![bradley cooper american sniper transformation steroids or somet 01-22-2015 15 36 19](https://cloud.githubusercontent.com/assets/970967/5856511/7f1efa24-a24c-11e4-89a6-63b91ffe56b5.png)
And I have good news for you.
Its user identifier is equal to 1 in drupal DB. This means that you are a super user (like root). Only you pass the access level of Drupal. So you only see this tab.
![people www fitnessjunkies com - google chrome 01-22-2015 15 39 33](https://cloud.githubusercontent.com/assets/970967/5856567/0ad76704-a24d-11e4-892e-2deec95b04bb.png)

**Comment by Fastone45** [comment]
That all looks good. Can we have a standard image that shows up for new profiles if they do not have a profile picture? I would like the profile picture to come from facebook, gmail or twitter if possible but if not I would like a standard logo. I will talk with the design to get a square logo for this and for the facebook posts that you mentioned before. We can close this issue now since you are waiting on me.

**Comment by mamont77** [comment]
Ryan, you can set "Default Image" here http://dev.fitnessjunkies.com/admin/config/people/accounts/fields/field_avatar/.

**Comment by Fastone45** [comment]
Ok, great!
